local settings = {
    backup = false,
    clipboard = "unnamedplus",
    cmdheight = 2,
    colorcolumn = "99999",
    completeopt = { "menuone", "noselect" },
    conceallevel = 0,
    fileencoding = "utf-8",
    foldmethod = "manual",
    foldexpr = "",
    guifont = "monospace:h17",
    hidden = true,
    hlsearch = true,
    ignorecase = true,
    mouse = "a",
    pumheight = 10,
    showmode = false,
    showtabline = 2,
    smartcase = true,
    smartindent = true,
    splitbelow = true,
    splitright = true,
    swapfile = false,
    termguicolors = true,
    timeoutlen = 100,
    title = true,
    -- opt.titlestring = "%<%F%=%l/%L - nvim"
    undofile = true,
    updatetime = 300,
    writebackup = false,
    autoread = true,
    expandtab = true,
    shiftwidth = 2,
    tabstop = 2,
    cursorline = true,
		relativenumber = true,
		number = true,
    numberwidth = 4,
    signcolumn = "yes",
    wrap = false,
    spell = false,
    spelllang = "en",
    scrolloff = 8,
    sidescrolloff = 8,
}

for k, v in pairs(settings) do
  vim.opt[k] = v
end

